//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayerUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLayerUtility.BusinessResources", typeof(BusinessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap AmountCollection {
            get {
                object obj = ResourceManager.GetObject("AmountCollection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Attendance {
            get {
                object obj = ResourceManager.GetObject("Attendance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Availability {
            get {
                object obj = ResourceManager.GetObject("Availability", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap B1 {
            get {
                object obj = ResourceManager.GetObject("B1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        public static string BACKGROUND_BLANKWHITE {
            get {
                return ResourceManager.GetString("BACKGROUND_BLANKWHITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1C2A4F.
        /// </summary>
        public static string BACKGROUND_COLOUR {
            get {
                return ResourceManager.GetString("BACKGROUND_COLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFCDD2.
        /// </summary>
        public static string BACKGROUND_NOTSUCCESS {
            get {
                return ResourceManager.GetString("BACKGROUND_NOTSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #AAF255.
        /// </summary>
        public static string BACKGROUND_SUCCESS {
            get {
                return ResourceManager.GetString("BACKGROUND_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BankDeposit {
            get {
                object obj = ResourceManager.GetObject("BankDeposit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BankWithdraw {
            get {
                object obj = ResourceManager.GetObject("BankWithdraw", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Add.
        /// </summary>
        public static string BTN_ADD {
            get {
                return ResourceManager.GetString("BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string BTN_BROWSE {
            get {
                return ResourceManager.GetString("BTN_BROWSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Excel File.
        /// </summary>
        public static string BTN_BROWSEEXCELFILE {
            get {
                return ResourceManager.GetString("BTN_BROWSEEXCELFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        public static string BTN_CLEAR {
            get {
                return ResourceManager.GetString("BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BTN_DELETE {
            get {
                return ResourceManager.GetString("BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string BTN_EXIT {
            get {
                return ResourceManager.GetString("BTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string BTN_INVOICE {
            get {
                return ResourceManager.GetString("BTN_INVOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string BTN_PLUS {
            get {
                return ResourceManager.GetString("BTN_PLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        public static string BTN_PRINT {
            get {
                return ResourceManager.GetString("BTN_PRINT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string BTN_REFRESH {
            get {
                return ResourceManager.GetString("BTN_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Report.
        /// </summary>
        public static string BTN_REPORT {
            get {
                return ResourceManager.GetString("BTN_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save In Tally.
        /// </summary>
        public static string BTN_SAVEINTALLY {
            get {
                return ResourceManager.GetString("BTN_SAVEINTALLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string BTN_SEARCH {
            get {
                return ResourceManager.GetString("BTN_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        public static string BTN_VIEW {
            get {
                return ResourceManager.GetString("BTN_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CapLabel {
            get {
                object obj = ResourceManager.GetObject("CapLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CapMaster {
            get {
                object obj = ResourceManager.GetObject("CapMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CategoryMaster {
            get {
                object obj = ResourceManager.GetObject("CategoryMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CheckIn {
            get {
                object obj = ResourceManager.GetObject("CheckIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap City {
            get {
                object obj = ResourceManager.GetObject("City", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Client_Requiremts {
            get {
                object obj = ResourceManager.GetObject("Client_Requiremts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ClientLogo {
            get {
                object obj = ResourceManager.GetObject("ClientLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ClientLogo_old {
            get {
                object obj = ResourceManager.GetObject("ClientLogo_old", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ClientLogo1 {
            get {
                object obj = ResourceManager.GetObject("ClientLogo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0000ff.
        /// </summary>
        public static string COL_LBL_HEADER {
            get {
                return ResourceManager.GetString("COL_LBL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Commercial {
            get {
                object obj = ResourceManager.GetObject("Commercial", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CreditNote {
            get {
                object obj = ResourceManager.GetObject("CreditNote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Customer {
            get {
                object obj = ResourceManager.GetObject("Customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vijay@007.
        /// </summary>
        public static string DATABASEPASSWORD {
            get {
                return ResourceManager.GetString("DATABASEPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D:\GitProjects\SKPI\SPApplication\SPApplication\bin\Debug\Data\Database\SKPIDB.mdb.
        /// </summary>
        public static string DATABASEPATH {
            get {
                return ResourceManager.GetString("DATABASEPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\192.168.1.3\d\Softwares\NewStickerPrinting\Software\Data\Database\SKPIDB.mdb.
        /// </summary>
        public static string DATABASEPATH_IP {
            get {
                return ResourceManager.GetString("DATABASEPATH_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\skpi\D\Softwares\Sticker Printing\Data\Database\SKPIDB.mdb.
        /// </summary>
        public static string DATABASEPATH_S {
            get {
                return ResourceManager.GetString("DATABASEPATH_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\192.168.1.3\d\Softwares\Sticker Printing\Data\Database\SKPIDB.mdb.
        /// </summary>
        public static string DATABASEPATH_SKPI {
            get {
                return ResourceManager.GetString("DATABASEPATH_SKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy hh:mm tt.
        /// </summary>
        public static string DATE_FORMAT_WITHTIME {
            get {
                return ResourceManager.GetString("DATE_FORMAT_WITHTIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm.
        /// </summary>
        public static string DATE_FORMAT_WITHTIME_DDMMYYYHHMM {
            get {
                return ResourceManager.GetString("DATE_FORMAT_WITHTIME_DDMMYYYHHMM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string DATEFORMATDDMMYYYY {
            get {
                return ResourceManager.GetString("DATEFORMATDDMMYYYY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        public static string DATEFORMATMMDDYYYY {
            get {
                return ResourceManager.GetString("DATEFORMATMMDDYYYY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Deposit {
            get {
                object obj = ResourceManager.GetObject("Deposit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DispatchEntry {
            get {
                object obj = ResourceManager.GetObject("DispatchEntry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DispatchSchedule {
            get {
                object obj = ResourceManager.GetObject("DispatchSchedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Employee {
            get {
                object obj = ResourceManager.GetObject("Employee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EventManagement {
            get {
                object obj = ResourceManager.GetObject("EventManagement", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap EventMaster {
            get {
                object obj = ResourceManager.GetObject("EventMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Expenses {
            get {
                object obj = ResourceManager.GetObject("Expenses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FirmInfo {
            get {
                object obj = ResourceManager.GetObject("FirmInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibri.
        /// </summary>
        public static string FONT_NAME {
            get {
                return ResourceManager.GetString("FONT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        public static string FORE_COLOUR {
            get {
                return ResourceManager.GetString("FORE_COLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Format\.
        /// </summary>
        public static string FORMATPATH {
            get {
                return ResourceManager.GetString("FORMATPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \\192.168.1.3\d\Softwares\Sticker Printing\Data\Format\.
        /// </summary>
        public static string FORMATPATH_SKPI {
            get {
                return ResourceManager.GetString("FORMATPATH_SKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string FRM_ITEM {
            get {
                return ResourceManager.GetString("FRM_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Details.
        /// </summary>
        public static string GB_CHEQUE_DETAILS {
            get {
                return ResourceManager.GetString("GB_CHEQUE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Details.
        /// </summary>
        public static string GR_ITEM_DETAILS {
            get {
                return ResourceManager.GetString("GR_ITEM_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price and Taxes.
        /// </summary>
        public static string GR_PRICING {
            get {
                return ResourceManager.GetString("GR_PRICING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string GR_TAXES {
            get {
                return ResourceManager.GetString("GR_TAXES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ICOLogo {
            get {
                object obj = ResourceManager.GetObject("ICOLogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap InventoryHub {
            get {
                object obj = ResourceManager.GetObject("InventoryHub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Item {
            get {
                object obj = ResourceManager.GetObject("Item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ItemRequisition {
            get {
                object obj = ResourceManager.GetObject("ItemRequisition", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap KanbanBoard {
            get {
                object obj = ResourceManager.GetObject("KanbanBoard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap KanBanSalesOrder {
            get {
                object obj = ResourceManager.GetObject("KanBanSalesOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string LBL_ADDRESS {
            get {
                return ResourceManager.GetString("LBL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LBL_AMOUNT {
            get {
                return ResourceManager.GetString("LBL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Amount.
        /// </summary>
        public static string LBL_BALANCE_AMOUNT {
            get {
                return ResourceManager.GetString("LBL_BALANCE_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string LBL_BANK_NAME {
            get {
                return ResourceManager.GetString("LBL_BANK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number.
        /// </summary>
        public static string LBL_BATCH_NUMBER {
            get {
                return ResourceManager.GetString("LBL_BATCH_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        public static string LBL_BRANCH_NAME {
            get {
                return ResourceManager.GetString("LBL_BRANCH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string LBL_BUTTON_SUPPLIER {
            get {
                return ResourceManager.GetString("LBL_BUTTON_SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LBL_CATEGORY {
            get {
                return ResourceManager.GetString("LBL_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGST In %.
        /// </summary>
        public static string LBL_CGST_PER {
            get {
                return ResourceManager.GetString("LBL_CGST_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No..
        /// </summary>
        public static string LBL_CHEQUE_NO {
            get {
                return ResourceManager.GetString("LBL_CHEQUE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string LBL_COMPANY_NAME {
            get {
                return ResourceManager.GetString("LBL_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile-9822837797.
        /// </summary>
        public static string LBL_CONTACTDETAILS {
            get {
                return ResourceManager.GetString("LBL_CONTACTDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contain.
        /// </summary>
        public static string LBL_CONTAIN {
            get {
                return ResourceManager.GetString("LBL_CONTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright @ 2020. 2dk Apps, Pune.
        /// </summary>
        public static string LBL_COPYRIGHTS {
            get {
                return ResourceManager.GetString("LBL_COPYRIGHTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string LBL_COST {
            get {
                return ResourceManager.GetString("LBL_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string LBL_CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string LBL_DASHBOARD_SALE {
            get {
                return ResourceManager.GetString("LBL_DASHBOARD_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LBL_DATE {
            get {
                return ResourceManager.GetString("LBL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shree Khodiyar Plastic Industries.
        /// </summary>
        public static string LBL_FIRMNAME {
            get {
                return ResourceManager.GetString("LBL_FIRMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Server Backup.
        /// </summary>
        public static string LBL_HEADER_ADDBACKUPFOLDER {
            get {
                return ResourceManager.GetString("LBL_HEADER_ADDBACKUPFOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string LBL_HEADER_ADDUSER {
            get {
                return ResourceManager.GetString("LBL_HEADER_ADDUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Collection.
        /// </summary>
        public static string LBL_HEADER_AMOUNTCOLLECTION {
            get {
                return ResourceManager.GetString("LBL_HEADER_AMOUNTCOLLECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Collection Report.
        /// </summary>
        public static string LBL_HEADER_AMOUNTCOLLECTIONREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_AMOUNTCOLLECTIONREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Task.
        /// </summary>
        public static string LBL_HEADER_ASSIGNTASK {
            get {
                return ResourceManager.GetString("LBL_HEADER_ASSIGNTASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string LBL_HEADER_BANKACCOUNT {
            get {
                return ResourceManager.GetString("LBL_HEADER_BANKACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Deposit.
        /// </summary>
        public static string LBL_HEADER_BANKDEPOSIT {
            get {
                return ResourceManager.GetString("LBL_HEADER_BANKDEPOSIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Deposit and Withdraw Report.
        /// </summary>
        public static string LBL_HEADER_BANKDEPOSITANDWITHDRAW {
            get {
                return ResourceManager.GetString("LBL_HEADER_BANKDEPOSITANDWITHDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Withdraw.
        /// </summary>
        public static string LBL_HEADER_BANKWITHDRAW {
            get {
                return ResourceManager.GetString("LBL_HEADER_BANKWITHDRAW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Report.
        /// </summary>
        public static string LBL_HEADER_BIRTHDAYREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_BIRTHDAYREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Checkin and Checkout Report.
        /// </summary>
        public static string LBL_HEADER_BOOKINGCHECKINCHECKOUTREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_BOOKINGCHECKINCHECKOUTREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap Label.
        /// </summary>
        public static string LBL_HEADER_CAPLABEL {
            get {
                return ResourceManager.GetString("LBL_HEADER_CAPLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cap Master.
        /// </summary>
        public static string LBL_HEADER_CAPMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_CAPMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categary.
        /// </summary>
        public static string LBL_HEADER_CATEGARY {
            get {
                return ResourceManager.GetString("LBL_HEADER_CATEGARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate of Analysis.
        /// </summary>
        public static string LBL_HEADER_CERTIFICATEOFANALYSIS {
            get {
                return ResourceManager.GetString("LBL_HEADER_CERTIFICATEOFANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string LBL_HEADER_CHANGEPASSWORD {
            get {
                return ResourceManager.GetString("LBL_HEADER_CHANGEPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In and Check Out.
        /// </summary>
        public static string LBL_HEADER_CHECKIN {
            get {
                return ResourceManager.GetString("LBL_HEADER_CHECKIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string LBL_HEADER_CITY {
            get {
                return ResourceManager.GetString("LBL_HEADER_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Requirements for Sales Order.
        /// </summary>
        public static string LBL_HEADER_CLIENTREQUIREMENTS {
            get {
                return ResourceManager.GetString("LBL_HEADER_CLIENTREQUIREMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Type Master.
        /// </summary>
        public static string LBL_HEADER_COLLECTIONTYPEMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_COLLECTIONTYPEMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial Order.
        /// </summary>
        public static string LBL_HEADER_COMMERCIALORDERKANBAN {
            get {
                return ResourceManager.GetString("LBL_HEADER_COMMERCIALORDERKANBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Return Note.
        /// </summary>
        public static string LBL_HEADER_CRNOTE {
            get {
                return ResourceManager.GetString("LBL_HEADER_CRNOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string LBL_HEADER_CUSTOMER {
            get {
                return ResourceManager.GetString("LBL_HEADER_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Payment Deposit Report.
        /// </summary>
        public static string LBL_HEADER_CUSTOMERPAYMENTDEPOSITREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_CUSTOMERPAYMENTDEPOSITREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Report.
        /// </summary>
        public static string LBL_HEADER_CUSTOMERREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_CUSTOMERREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Book Entry.
        /// </summary>
        public static string LBL_HEADER_DAILYBOOKENTRY {
            get {
                return ResourceManager.GetString("LBL_HEADER_DAILYBOOKENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Head.
        /// </summary>
        public static string LBL_HEADER_DEPOSITHEAD {
            get {
                return ResourceManager.GetString("LBL_HEADER_DEPOSITHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatch Schedule.
        /// </summary>
        public static string LBL_HEADER_DISPATCHSCHEDULE {
            get {
                return ResourceManager.GetString("LBL_HEADER_DISPATCHSCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part / Equipment Due Date Report.
        /// </summary>
        public static string LBL_HEADER_DUEDATEREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_DUEDATEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Credentials.
        /// </summary>
        public static string LBL_HEADER_EMAILCREDENTIALS {
            get {
                return ResourceManager.GetString("LBL_HEADER_EMAILCREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string LBL_HEADER_EMPLOYEE {
            get {
                return ResourceManager.GetString("LBL_HEADER_EMPLOYEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Attendance.
        /// </summary>
        public static string LBL_HEADER_EMPLOYEE_ATTEMDAMCE {
            get {
                return ResourceManager.GetString("LBL_HEADER_EMPLOYEE_ATTEMDAMCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Temperature.
        /// </summary>
        public static string LBL_HEADER_EMPLOYEETEMPERATURE {
            get {
                return ResourceManager.GetString("LBL_HEADER_EMPLOYEETEMPERATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Booking.
        /// </summary>
        public static string LBL_HEADER_EVENT_MANAGEMENT {
            get {
                return ResourceManager.GetString("LBL_HEADER_EVENT_MANAGEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events Booking.
        /// </summary>
        public static string LBL_HEADER_EVENTBOOKING {
            get {
                return ResourceManager.GetString("LBL_HEADER_EVENTBOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Booking Report.
        /// </summary>
        public static string LBL_HEADER_EVENTBOOKINGREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_EVENTBOOKINGREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Master.
        /// </summary>
        public static string LBL_HEADER_EVENTMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_EVENTMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Head.
        /// </summary>
        public static string LBL_HEADER_EXPENSES {
            get {
                return ResourceManager.GetString("LBL_HEADER_EXPENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Head.
        /// </summary>
        public static string LBL_HEADER_EXPENSESHEAD {
            get {
                return ResourceManager.GetString("LBL_HEADER_EXPENSESHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Report.
        /// </summary>
        public static string LBL_HEADER_EXPENSESREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_EXPENSESREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Information.
        /// </summary>
        public static string LBL_HEADER_FIRMINFORMATION {
            get {
                return ResourceManager.GetString("LBL_HEADER_FIRMINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Data From Tally Software.
        /// </summary>
        public static string LBL_HEADER_GETTALLYDATA {
            get {
                return ResourceManager.GetString("LBL_HEADER_GETTALLYDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade Notice Bord Report.
        /// </summary>
        public static string LBL_HEADER_GradeNoticeBordReport {
            get {
                return ResourceManager.GetString("LBL_HEADER_GradeNoticeBordReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Report.
        /// </summary>
        public static string LBL_HEADER_GSTREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_GSTREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Table Master.
        /// </summary>
        public static string LBL_HEADER_HOTELTABLE {
            get {
                return ResourceManager.GetString("LBL_HEADER_HOTELTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inward Material.
        /// </summary>
        public static string LBL_HEADER_INWARDMATERIAL {
            get {
                return ResourceManager.GetString("LBL_HEADER_INWARDMATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string LBL_HEADER_ITEM {
            get {
                return ResourceManager.GetString("LBL_HEADER_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Master.
        /// </summary>
        public static string LBL_HEADER_ITEMMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_ITEMMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity Report.
        /// </summary>
        public static string LBL_HEADER_ITEMQUANTITYREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_ITEMQUANTITYREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Window.
        /// </summary>
        public static string LBL_HEADER_LOGINWINDOW {
            get {
                return ResourceManager.GetString("LBL_HEADER_LOGINWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Master.
        /// </summary>
        public static string LBL_HEADER_MACHINEMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_MACHINEMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufracturing .
        /// </summary>
        public static string LBL_HEADER_MANUFACTURINGORDERKANBAN {
            get {
                return ResourceManager.GetString("LBL_HEADER_MANUFACTURINGORDERKANBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufracturer.
        /// </summary>
        public static string LBL_HEADER_MANUFRACTURER {
            get {
                return ResourceManager.GetString("LBL_HEADER_MANUFRACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Production Report.
        /// </summary>
        public static string LBL_HEADER_MONTHLYPRODUCTIONREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_MONTHLYPRODUCTIONREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mould Master.
        /// </summary>
        public static string LBL_HEADER_MOULDMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_MOULDMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Equipment Effectiveness (OEE).
        /// </summary>
        public static string LBL_HEADER_OEE {
            get {
                return ResourceManager.GetString("LBL_HEADER_OEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Stock Entry.
        /// </summary>
        public static string LBL_HEADER_OPENINGSTOCKENTRY {
            get {
                return ResourceManager.GetString("LBL_HEADER_OPENINGSTOCKENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outward Material.
        /// </summary>
        public static string LBL_HEADER_OUTWARDMATERIAL {
            get {
                return ResourceManager.GetString("LBL_HEADER_OUTWARDMATERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Master.
        /// </summary>
        public static string LBL_HEADER_PACKAGEMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_PACKAGEMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment / Part Master.
        /// </summary>
        public static string LBL_HEADER_PARTEQUIPMENT {
            get {
                return ResourceManager.GetString("LBL_HEADER_PARTEQUIPMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part / Equipment / Software / Hardware Renewal Entry.
        /// </summary>
        public static string LBL_HEADER_PARTEQUIPMENTENTRY {
            get {
                return ResourceManager.GetString("LBL_HEADER_PARTEQUIPMENTENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string LBL_HEADER_PAYMENT {
            get {
                return ResourceManager.GetString("LBL_HEADER_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place or Rack/Box Master.
        /// </summary>
        public static string LBL_HEADER_PLACEMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_PLACEMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLANNER.
        /// </summary>
        public static string LBL_HEADER_PLANNER {
            get {
                return ResourceManager.GetString("LBL_HEADER_PLANNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preform Master.
        /// </summary>
        public static string LBL_HEADER_PREFORM {
            get {
                return ResourceManager.GetString("LBL_HEADER_PREFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preform Party Master.
        /// </summary>
        public static string LBL_HEADER_PREFORMPARTY {
            get {
                return ResourceManager.GetString("LBL_HEADER_PREFORMPARTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Quantity Report.
        /// </summary>
        public static string LBL_HEADER_PRODUCTION_QUANTITY_REPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_PRODUCTION_QUANTITY_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Label.
        /// </summary>
        public static string LBL_HEADER_PRODUCTIONLABEL {
            get {
                return ResourceManager.GetString("LBL_HEADER_PRODUCTIONLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string LBL_HEADER_PRODUCTIONORDERKANBAN {
            get {
                return ResourceManager.GetString("LBL_HEADER_PRODUCTIONORDERKANBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product&apos;s Standard and Tolerance Messurements.
        /// </summary>
        public static string LBL_HEADER_PRODUCTTOLLARANCEVALUE {
            get {
                return ResourceManager.GetString("LBL_HEADER_PRODUCTTOLLARANCEVALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Switch Reason.
        /// </summary>
        public static string LBL_HEADER_PRODUCUSWITCHREASON {
            get {
                return ResourceManager.GetString("LBL_HEADER_PRODUCUSWITCHREASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit and Loss.
        /// </summary>
        public static string LBL_HEADER_PROFITANDREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_PROFITANDREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puchase.
        /// </summary>
        public static string LBL_HEADER_PURCHASE {
            get {
                return ResourceManager.GetString("LBL_HEADER_PURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Requirements for Purchase Order.
        /// </summary>
        public static string LBL_HEADER_PURCHASEORDER {
            get {
                return ResourceManager.GetString("LBL_HEADER_PURCHASEORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Report.
        /// </summary>
        public static string LBL_HEADER_PURCHASEREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_PURCHASEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string LBL_HEADER_PURCHASESORDERKANBAN {
            get {
                return ResourceManager.GetString("LBL_HEADER_PURCHASESORDERKANBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control Register Entry.
        /// </summary>
        public static string LBL_HEADER_QUALITY_CONTROL_REGISTER_ENTRY {
            get {
                return ResourceManager.GetString("LBL_HEADER_QUALITY_CONTROL_REGISTER_ENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Analysis.
        /// </summary>
        public static string LBL_HEADER_QUALITYANALYSIS {
            get {
                return ResourceManager.GetString("LBL_HEADER_QUALITYANALYSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control Product Wise Report.
        /// </summary>
        public static string LBL_HEADER_QUALITYCONTROLPRODUCTWISEREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_QUALITYCONTROLPRODUCTWISEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string LBL_HEADER_RECEIPT {
            get {
                return ResourceManager.GetString("LBL_HEADER_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report List.
        /// </summary>
        public static string LBL_HEADER_REPORTLIST {
            get {
                return ResourceManager.GetString("LBL_HEADER_REPORTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant Bill.
        /// </summary>
        public static string LBL_HEADER_RESTAURANTBILL {
            get {
                return ResourceManager.GetString("LBL_HEADER_RESTAURANTBILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string LBL_HEADER_ROOM {
            get {
                return ResourceManager.GetString("LBL_HEADER_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kanban Sales Order 1.
        /// </summary>
        public static string LBL_HEADER_SALESORDERKANBAN {
            get {
                return ResourceManager.GetString("LBL_HEADER_SALESORDERKANBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings List.
        /// </summary>
        public static string LBL_HEADER_SETTINGSLIST {
            get {
                return ResourceManager.GetString("LBL_HEADER_SETTINGSLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Entry.
        /// </summary>
        public static string LBL_HEADER_SHIFTENTRY {
            get {
                return ResourceManager.GetString("LBL_HEADER_SHIFTENTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift Schedule.
        /// </summary>
        public static string LBL_HEADER_SHIFTSCHEDULE {
            get {
                return ResourceManager.GetString("LBL_HEADER_SHIFTSCHEDULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Attendance Report.
        /// </summary>
        public static string LBL_HEADER_STUDENTATTENDANCEREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_STUDENTATTENDANCEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string LBL_HEADER_SUPPLIER {
            get {
                return ResourceManager.GetString("LBL_HEADER_SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Payment Deposit Report.
        /// </summary>
        public static string LBL_HEADER_SUPPLIERDETAILS {
            get {
                return ResourceManager.GetString("LBL_HEADER_SUPPLIERDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Report.
        /// </summary>
        public static string LBL_HEADER_SUPPLIERREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_SUPPLIERREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Task Master.
        /// </summary>
        public static string LBL_HEADER_TASKMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_TASKMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Messurement.
        /// </summary>
        public static string LBL_HEADER_UOM {
            get {
                return ResourceManager.GetString("LBL_HEADER_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used For Master.
        /// </summary>
        public static string LBL_HEADER_USEDFOR {
            get {
                return ResourceManager.GetString("LBL_HEADER_USEDFOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Master.
        /// </summary>
        public static string LBL_HEADER_USER {
            get {
                return ResourceManager.GetString("LBL_HEADER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAD Master.
        /// </summary>
        public static string LBL_HEADER_WADMASTER {
            get {
                return ResourceManager.GetString("LBL_HEADER_WADMASTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        public static string LBL_HELP {
            get {
                return ResourceManager.GetString("LBL_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSN Code (GST).
        /// </summary>
        public static string LBL_HSN_CODE {
            get {
                return ResourceManager.GetString("LBL_HSN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGST In %.
        /// </summary>
        public static string LBL_IGST_PER {
            get {
                return ResourceManager.GetString("LBL_IGST_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string LBL_ITEM_NAME {
            get {
                return ResourceManager.GetString("LBL_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Requisition.
        /// </summary>
        public static string LBL_ItemRequisition {
            get {
                return ResourceManager.GetString("LBL_ItemRequisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufracturer Master.
        /// </summary>
        public static string LBL_Manufracturer {
            get {
                return ResourceManager.GetString("LBL_Manufracturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRP.
        /// </summary>
        public static string LBL_MRP {
            get {
                return ResourceManager.GetString("LBL_MRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode.
        /// </summary>
        public static string LBL_PAYMENT_MODE {
            get {
                return ResourceManager.GetString("LBL_PAYMENT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string LBL_PRICE {
            get {
                return ResourceManager.GetString("LBL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Margin Amount.
        /// </summary>
        public static string LBL_PROFIT_MARGIN_AMOUNT {
            get {
                return ResourceManager.GetString("LBL_PROFIT_MARGIN_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Margin In %.
        /// </summary>
        public static string LBL_PROFIT_MARGIN_PER {
            get {
                return ResourceManager.GetString("LBL_PROFIT_MARGIN_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress Card Report.
        /// </summary>
        public static string LBL_PROGRESSCARD_REPORT {
            get {
                return ResourceManager.GetString("LBL_PROGRESSCARD_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Wise Quality Control Report.
        /// </summary>
        public static string LBL_REPORT_BATCHWISEQUALITYCONTROLREPORT {
            get {
                return ResourceManager.GetString("LBL_REPORT_BATCHWISEQUALITYCONTROLREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Attendance Monthwise Report.
        /// </summary>
        public static string LBL_REPORT_EMPLOYEE_MONTHWISE {
            get {
                return ResourceManager.GetString("LBL_REPORT_EMPLOYEE_MONTHWISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Temperature Report.
        /// </summary>
        public static string LBL_REPORT_EMPLOYEETEMPERATUREREPORT {
            get {
                return ResourceManager.GetString("LBL_REPORT_EMPLOYEETEMPERATUREREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Report.
        /// </summary>
        public static string LBL_REPORT_LOGREPORT {
            get {
                return ResourceManager.GetString("LBL_REPORT_LOGREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Outward Report.
        /// </summary>
        public static string LBL_REPORT_MATERIALOUTWARDREPORT {
            get {
                return ResourceManager.GetString("LBL_REPORT_MATERIALOUTWARDREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control Machine Wise Report.
        /// </summary>
        public static string LBL_REPORT_QUALITYCONTROLMACHINEWISEREPORT {
            get {
                return ResourceManager.GetString("LBL_REPORT_QUALITYCONTROLMACHINEWISEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s Task Assign Report.
        /// </summary>
        public static string LBL_REPORT_USERSTASKREPORT {
            get {
                return ResourceManager.GetString("LBL_REPORT_USERSTASKREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Item.
        /// </summary>
        public static string LBL_SEARCH_ITEM {
            get {
                return ResourceManager.GetString("LBL_SEARCH_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGST In %.
        /// </summary>
        public static string LBL_SGST_PER {
            get {
                return ResourceManager.GetString("LBL_SGST_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string LBL_SUPPLIER_NAME {
            get {
                return ResourceManager.GetString("LBL_SUPPLIER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string LBL_TEST {
            get {
                return ResourceManager.GetString("LBL_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string LBL_TOTAL_AMOUNT {
            get {
                return ResourceManager.GetString("LBL_TOTAL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pending.
        /// </summary>
        public static string LBL_TOTAL_PENDING {
            get {
                return ResourceManager.GetString("LBL_TOTAL_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Messurement.
        /// </summary>
        public static string LBL_UOM {
            get {
                return ResourceManager.GetString("LBL_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 8.0.12.
        /// </summary>
        public static string LBL_VERSION {
            get {
                return ResourceManager.GetString("LBL_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Availability.
        /// </summary>
        public static string LIST_REPORT_CHECKAVAILABILITY {
            get {
                return ResourceManager.GetString("LIST_REPORT_CHECKAVAILABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Payment Due Date Report.
        /// </summary>
        public static string LIST_REPORT_CLIENTPAYMENTDUEDATEREPORT {
            get {
                return ResourceManager.GetString("LIST_REPORT_CLIENTPAYMENTDUEDATEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity Report.
        /// </summary>
        public static string LIST_REPORT_ITEMQUANTITYREPORT {
            get {
                return ResourceManager.GetString("LIST_REPORT_ITEMQUANTITYREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity Report.
        /// </summary>
        public static string LIST_REPORT_ITEMQUANTITYREPORT1 {
            get {
                return ResourceManager.GetString("LIST_REPORT_ITEMQUANTITYREPORT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Report.
        /// </summary>
        public static string LIST_REPORT_SALESREPORT {
            get {
                return ResourceManager.GetString("LIST_REPORT_SALESREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MachineMaster {
            get {
                object obj = ResourceManager.GetObject("MachineMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Maintenance {
            get {
                object obj = ResourceManager.GetObject("Maintenance", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Manufacturing {
            get {
                object obj = ResourceManager.GetObject("Manufacturing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ManufacturingOrder {
            get {
                object obj = ResourceManager.GetObject("ManufacturingOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Manufracturer {
            get {
                object obj = ResourceManager.GetObject("Manufracturer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Masters {
            get {
                object obj = ResourceManager.GetObject("Masters", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MouldMaster {
            get {
                object obj = ResourceManager.GetObject("MouldMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OEE {
            get {
                object obj = ResourceManager.GetObject("OEE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OtherProducts {
            get {
                object obj = ResourceManager.GetObject("OtherProducts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Outward {
            get {
                object obj = ResourceManager.GetObject("Outward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PackageMaster {
            get {
                object obj = ResourceManager.GetObject("PackageMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PartMaster {
            get {
                object obj = ResourceManager.GetObject("PartMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Payment {
            get {
                object obj = ResourceManager.GetObject("Payment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PlaceMaster {
            get {
                object obj = ResourceManager.GetObject("PlaceMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Planner {
            get {
                object obj = ResourceManager.GetObject("Planner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preform {
            get {
                object obj = ResourceManager.GetObject("Preform", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PreformSupplier {
            get {
                object obj = ResourceManager.GetObject("PreformSupplier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Product {
            get {
                object obj = ResourceManager.GetObject("Product", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ProductionLabel {
            get {
                object obj = ResourceManager.GetObject("ProductionLabel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ProductionOrder {
            get {
                object obj = ResourceManager.GetObject("ProductionOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ProductLogo {
            get {
                object obj = ResourceManager.GetObject("ProductLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ProductLogo1 {
            get {
                object obj = ResourceManager.GetObject("ProductLogo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Purchase {
            get {
                object obj = ResourceManager.GetObject("Purchase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap purchase_order {
            get {
                object obj = ResourceManager.GetObject("purchase_order", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PurchaseOrder {
            get {
                object obj = ResourceManager.GetObject("PurchaseOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PurchaseReturn {
            get {
                object obj = ResourceManager.GetObject("PurchaseReturn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap QualityControl {
            get {
                object obj = ResourceManager.GetObject("QualityControl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEE Report Machine Wise.
        /// </summary>
        public static string R_OEEReportMachineWise {
            get {
                return ResourceManager.GetString("R_OEEReportMachineWise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Receipts {
            get {
                object obj = ResourceManager.GetObject("Receipts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Renewal {
            get {
                object obj = ResourceManager.GetObject("Renewal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Wise Quality Control Report.
        /// </summary>
        public static string Report_BatchWiseQualityControlReport {
            get {
                return ResourceManager.GetString("Report_BatchWiseQualityControlReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Wise Quality Control Report.
        /// </summary>
        public static string Report_ProductWiseQualityControlReport {
            get {
                return ResourceManager.GetString("Report_ProductWiseQualityControlReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reports {
            get {
                object obj = ResourceManager.GetObject("Reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Room {
            get {
                object obj = ResourceManager.GetObject("Room", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sale {
            get {
                object obj = ResourceManager.GetObject("Sale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SalesReturn {
            get {
                object obj = ResourceManager.GetObject("SalesReturn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ShiftSchedule {
            get {
                object obj = ResourceManager.GetObject("ShiftSchedule", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall Equipment Effectiveness Calculation.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Supplier {
            get {
                object obj = ResourceManager.GetObject("Supplier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Task {
            get {
                object obj = ResourceManager.GetObject("Task", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TaskMaster {
            get {
                object obj = ResourceManager.GetObject("TaskMaster", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Temperature {
            get {
                object obj = ResourceManager.GetObject("Temperature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm:ss.
        /// </summary>
        public static string TIME_FORMAT_HHMM_12 {
            get {
                return ResourceManager.GetString("TIME_FORMAT_HHMM_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string TIME_FORMAT_HHMM_24 {
            get {
                return ResourceManager.GetString("TIME_FORMAT_HHMM_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Transaction {
            get {
                object obj = ResourceManager.GetObject("Transaction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UOM {
            get {
                object obj = ResourceManager.GetObject("UOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UsedFor {
            get {
                object obj = ResourceManager.GetObject("UsedFor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string USER_ACCOUNTS {
            get {
                return ResourceManager.GetString("USER_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts1.
        /// </summary>
        public static string USER_ACCOUNTS1 {
            get {
                return ResourceManager.GetString("USER_ACCOUNTS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string USER_ADMIN {
            get {
                return ResourceManager.GetString("USER_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajay.
        /// </summary>
        public static string USER_AJAY {
            get {
                return ResourceManager.GetString("USER_AJAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hr.
        /// </summary>
        public static string USER_HR {
            get {
                return ResourceManager.GetString("USER_HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hr1.
        /// </summary>
        public static string USER_HR1 {
            get {
                return ResourceManager.GetString("USER_HR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IT.
        /// </summary>
        public static string USER_IT {
            get {
                return ResourceManager.GetString("USER_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string USER_LOGISTICS {
            get {
                return ResourceManager.GetString("USER_LOGISTICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string USER_MAINTENANCE {
            get {
                return ResourceManager.GetString("USER_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string USER_PRODUCTION {
            get {
                return ResourceManager.GetString("USER_PRODUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC.
        /// </summary>
        public static string USER_QC {
            get {
                return ResourceManager.GetString("USER_QC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        public static string USER_STORE {
            get {
                return ResourceManager.GetString("USER_STORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vijay.
        /// </summary>
        public static string USER_VIJAY {
            get {
                return ResourceManager.GetString("USER_VIJAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap WhatsAppImage {
            get {
                object obj = ResourceManager.GetObject("WhatsAppImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
