//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayerUtility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessLayerUtility.BusinessResources", typeof(BusinessResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1C2A4F.
        /// </summary>
        public static string BACKGROUND_COLOUR {
            get {
                return ResourceManager.GetString("BACKGROUND_COLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        public static string BTN_CLEAR {
            get {
                return ResourceManager.GetString("BTN_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BTN_DELETE {
            get {
                return ResourceManager.GetString("BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string BTN_EXIT {
            get {
                return ResourceManager.GetString("BTN_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        public static string BTN_PLUS {
            get {
                return ResourceManager.GetString("BTN_PLUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Report.
        /// </summary>
        public static string BTN_REPORT {
            get {
                return ResourceManager.GetString("BTN_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string BTN_SAVE {
            get {
                return ResourceManager.GetString("BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;View.
        /// </summary>
        public static string BTN_VIEW {
            get {
                return ResourceManager.GetString("BTN_VIEW", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap ClientLogo {
            get {
                object obj = ResourceManager.GetObject("ClientLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0000ff.
        /// </summary>
        public static string COL_LBL_HEADER {
            get {
                return ResourceManager.GetString("COL_LBL_HEADER", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap CreditNote {
            get {
                object obj = ResourceManager.GetObject("CreditNote", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Customer {
            get {
                object obj = ResourceManager.GetObject("Customer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Deposit {
            get {
                object obj = ResourceManager.GetObject("Deposit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Expenses {
            get {
                object obj = ResourceManager.GetObject("Expenses", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap FirmInfo {
            get {
                object obj = ResourceManager.GetObject("FirmInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibri.
        /// </summary>
        public static string FONT_NAME {
            get {
                return ResourceManager.GetString("FONT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFFFFF.
        /// </summary>
        public static string FORE_COLOUR {
            get {
                return ResourceManager.GetString("FORE_COLOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string FRM_ITEM {
            get {
                return ResourceManager.GetString("FRM_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque Details.
        /// </summary>
        public static string GB_CHEQUE_DETAILS {
            get {
                return ResourceManager.GetString("GB_CHEQUE_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Details.
        /// </summary>
        public static string GR_ITEM_DETAILS {
            get {
                return ResourceManager.GetString("GR_ITEM_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price and Taxes.
        /// </summary>
        public static string GR_PRICING {
            get {
                return ResourceManager.GetString("GR_PRICING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string GR_TAXES {
            get {
                return ResourceManager.GetString("GR_TAXES", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Item {
            get {
                object obj = ResourceManager.GetObject("Item", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string LBL_ADDRESS {
            get {
                return ResourceManager.GetString("LBL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LBL_AMOUNT {
            get {
                return ResourceManager.GetString("LBL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Amount.
        /// </summary>
        public static string LBL_BALANCE_AMOUNT {
            get {
                return ResourceManager.GetString("LBL_BALANCE_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        public static string LBL_BANK_NAME {
            get {
                return ResourceManager.GetString("LBL_BANK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Number.
        /// </summary>
        public static string LBL_BATCH_NUMBER {
            get {
                return ResourceManager.GetString("LBL_BATCH_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name.
        /// </summary>
        public static string LBL_BRANCH_NAME {
            get {
                return ResourceManager.GetString("LBL_BRANCH_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string LBL_BUTTON_SUPPLIER {
            get {
                return ResourceManager.GetString("LBL_BUTTON_SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LBL_CATEGORY {
            get {
                return ResourceManager.GetString("LBL_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CGST In %.
        /// </summary>
        public static string LBL_CGST_PER {
            get {
                return ResourceManager.GetString("LBL_CGST_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheque No..
        /// </summary>
        public static string LBL_CHEQUE_NO {
            get {
                return ResourceManager.GetString("LBL_CHEQUE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string LBL_COMPANY_NAME {
            get {
                return ResourceManager.GetString("LBL_COMPANY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contain.
        /// </summary>
        public static string LBL_CONTAIN {
            get {
                return ResourceManager.GetString("LBL_CONTAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string LBL_COST {
            get {
                return ResourceManager.GetString("LBL_COST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string LBL_CUSTOMER_NAME {
            get {
                return ResourceManager.GetString("LBL_CUSTOMER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string LBL_DASHBOARD_SALE {
            get {
                return ResourceManager.GetString("LBL_DASHBOARD_SALE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LBL_DATE {
            get {
                return ResourceManager.GetString("LBL_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string LBL_HEADER_ADDUSER {
            get {
                return ResourceManager.GetString("LBL_HEADER_ADDUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account.
        /// </summary>
        public static string LBL_HEADER_BANKACCOUNT {
            get {
                return ResourceManager.GetString("LBL_HEADER_BANKACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Report.
        /// </summary>
        public static string LBL_HEADER_BIRTHDAYREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_BIRTHDAYREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string LBL_HEADER_CHANGEPASSWORD {
            get {
                return ResourceManager.GetString("LBL_HEADER_CHANGEPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Return Note.
        /// </summary>
        public static string LBL_HEADER_CRNOTE {
            get {
                return ResourceManager.GetString("LBL_HEADER_CRNOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string LBL_HEADER_CUSTOMER {
            get {
                return ResourceManager.GetString("LBL_HEADER_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Payment Deposit Report.
        /// </summary>
        public static string LBL_HEADER_CUSTOMERPAYMENTDEPOSITREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_CUSTOMERPAYMENTDEPOSITREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Report.
        /// </summary>
        public static string LBL_HEADER_CUSTOMERREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_CUSTOMERREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Head.
        /// </summary>
        public static string LBL_HEADER_DEPOSITHEAD {
            get {
                return ResourceManager.GetString("LBL_HEADER_DEPOSITHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Credentials.
        /// </summary>
        public static string LBL_HEADER_EMAILCREDENTIALS {
            get {
                return ResourceManager.GetString("LBL_HEADER_EMAILCREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Head.
        /// </summary>
        public static string LBL_HEADER_EXPENSES {
            get {
                return ResourceManager.GetString("LBL_HEADER_EXPENSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Head.
        /// </summary>
        public static string LBL_HEADER_EXPENSESHEAD {
            get {
                return ResourceManager.GetString("LBL_HEADER_EXPENSESHEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses Report.
        /// </summary>
        public static string LBL_HEADER_EXPENSESREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_EXPENSESREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firm Information.
        /// </summary>
        public static string LBL_HEADER_FIRMINFORMATION {
            get {
                return ResourceManager.GetString("LBL_HEADER_FIRMINFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Report.
        /// </summary>
        public static string LBL_HEADER_GSTREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_GSTREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity Report.
        /// </summary>
        public static string LBL_HEADER_ITEMQUANTITYREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_ITEMQUANTITYREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Window.
        /// </summary>
        public static string LBL_HEADER_LOGINWINDOW {
            get {
                return ResourceManager.GetString("LBL_HEADER_LOGINWINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufracturer.
        /// </summary>
        public static string LBL_HEADER_MANUFRACTURER {
            get {
                return ResourceManager.GetString("LBL_HEADER_MANUFRACTURER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string LBL_HEADER_PAYMENT {
            get {
                return ResourceManager.GetString("LBL_HEADER_PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit and Loss.
        /// </summary>
        public static string LBL_HEADER_PROFITANDREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_PROFITANDREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puchase.
        /// </summary>
        public static string LBL_HEADER_PURCHASE {
            get {
                return ResourceManager.GetString("LBL_HEADER_PURCHASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Report.
        /// </summary>
        public static string LBL_HEADER_PURCHASEREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_PURCHASEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string LBL_HEADER_RECEIPT {
            get {
                return ResourceManager.GetString("LBL_HEADER_RECEIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report List.
        /// </summary>
        public static string LBL_HEADER_REPORTLIST {
            get {
                return ResourceManager.GetString("LBL_HEADER_REPORTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings List.
        /// </summary>
        public static string LBL_HEADER_SETTINGSLIST {
            get {
                return ResourceManager.GetString("LBL_HEADER_SETTINGSLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string LBL_HEADER_SUPPLIER {
            get {
                return ResourceManager.GetString("LBL_HEADER_SUPPLIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Payment Deposit Report.
        /// </summary>
        public static string LBL_HEADER_SUPPLIERDETAILS {
            get {
                return ResourceManager.GetString("LBL_HEADER_SUPPLIERDETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Report.
        /// </summary>
        public static string LBL_HEADER_SUPPLIERREPORT {
            get {
                return ResourceManager.GetString("LBL_HEADER_SUPPLIERREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Messurement.
        /// </summary>
        public static string LBL_HEADER_UOM {
            get {
                return ResourceManager.GetString("LBL_HEADER_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HSN Code (GST).
        /// </summary>
        public static string LBL_HSN_CODE {
            get {
                return ResourceManager.GetString("LBL_HSN_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IGST In %.
        /// </summary>
        public static string LBL_IGST_PER {
            get {
                return ResourceManager.GetString("LBL_IGST_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string LBL_ITEM_NAME {
            get {
                return ResourceManager.GetString("LBL_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRP.
        /// </summary>
        public static string LBL_MRP {
            get {
                return ResourceManager.GetString("LBL_MRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Mode.
        /// </summary>
        public static string LBL_PAYMENT_MODE {
            get {
                return ResourceManager.GetString("LBL_PAYMENT_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string LBL_PRICE {
            get {
                return ResourceManager.GetString("LBL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Margin Amount.
        /// </summary>
        public static string LBL_PROFIT_MARGIN_AMOUNT {
            get {
                return ResourceManager.GetString("LBL_PROFIT_MARGIN_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit Margin In %.
        /// </summary>
        public static string LBL_PROFIT_MARGIN_PER {
            get {
                return ResourceManager.GetString("LBL_PROFIT_MARGIN_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Item.
        /// </summary>
        public static string LBL_SEARCH_ITEM {
            get {
                return ResourceManager.GetString("LBL_SEARCH_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SGST In %.
        /// </summary>
        public static string LBL_SGST_PER {
            get {
                return ResourceManager.GetString("LBL_SGST_PER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string LBL_SUPPLIER_NAME {
            get {
                return ResourceManager.GetString("LBL_SUPPLIER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string LBL_TEST {
            get {
                return ResourceManager.GetString("LBL_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string LBL_TOTAL_AMOUNT {
            get {
                return ResourceManager.GetString("LBL_TOTAL_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Pending.
        /// </summary>
        public static string LBL_TOTAL_PENDING {
            get {
                return ResourceManager.GetString("LBL_TOTAL_PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit of Messurement.
        /// </summary>
        public static string LBL_UOM {
            get {
                return ResourceManager.GetString("LBL_UOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Quantity Report.
        /// </summary>
        public static string LIST_REPORT_ITEMQUANTITYREPORT {
            get {
                return ResourceManager.GetString("LIST_REPORT_ITEMQUANTITYREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Report.
        /// </summary>
        public static string LIST_REPORT_SALESREPORT {
            get {
                return ResourceManager.GetString("LIST_REPORT_SALESREPORT", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Manufracturer {
            get {
                object obj = ResourceManager.GetObject("Manufracturer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Masters {
            get {
                object obj = ResourceManager.GetObject("Masters", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Payment {
            get {
                object obj = ResourceManager.GetObject("Payment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap ProductLogo {
            get {
                object obj = ResourceManager.GetObject("ProductLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Purchase {
            get {
                object obj = ResourceManager.GetObject("Purchase", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Receipts {
            get {
                object obj = ResourceManager.GetObject("Receipts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Reports {
            get {
                object obj = ResourceManager.GetObject("Reports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Sale {
            get {
                object obj = ResourceManager.GetObject("Sale", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Settings {
            get {
                object obj = ResourceManager.GetObject("Settings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Supplier {
            get {
                object obj = ResourceManager.GetObject("Supplier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap Transaction {
            get {
                object obj = ResourceManager.GetObject("Transaction", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Bitmap UOM {
            get {
                object obj = ResourceManager.GetObject("UOM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
